
server:
  port: 8888

eureka:
  instance:
    prefer-ip-address: true
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://eureka-host-01:18761/eureka/,http://eureka-host-02:18762/eureka/,http://eureka-host-03:18763/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
        #exclude: "env,beans"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

####
#Classpath and file-based solution
####

#server:
#   port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#     config:
#       server:
#           native:
#              searchLocations: file://<esam-configuration>/confsvr/src/main/resources/config/requestservice,
#                               file://<esam-configuration>confsvr/src/main/resources/config/resourceservice
###              #searchLocations: classpath:config/,classpath:config/requestservice
